Updated readme
zameel7/bulk-certificate pull request #4
Opened 2022-10-17 17:22 UTC by JoydeepMallick

Added documentation as much as possible.

2022-10-17 17:25 UTC, zameel7 requested changes
Could you please check for grammar errors?

2022-10-18 02:17 UTC, zameel7 requested changes
Could you remove that last image you've added from the colab? or else could you add all the images from the colab along with the steps you mentioned?
And please remove that source line at the bottom😃

2022-10-18 03:27 UTC, JoydeepMallick commented
yes, am working on it

On Tue, Oct 18, 2022 at 7:47 AM Zameel Hassan ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Could you remove that last image you've added from the colab? or else
> could you add all the images from the colab along with the steps you
> mentioned?
> And please remove that source line at the bottom😃
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zameel7/bulk-certificate/pull/4#pullrequestreview-1145003210>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWTJAIFGFRZRK5VIGQKUVDDWDYCD5ANCNFSM6AAAAAARHJBOPQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-18 03:30 UTC, zameel7 approved these changes

2022-10-18 03:31 UTC, merged